account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user/', views.UserView.as_view(), name='user'),
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('user/<str:slug>/', views.UserDetailView.as_view(), name='user_detail'),
]

chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ChannelView.as_view(), name='channel'),
    path('new/<int:pk>/', views.NewChannelView.as_view(), name='new_channel'),
]

elcats/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chat/', include('chat.urls')),

    path('', include('account.urls')),
    path('', include('schedule.urls')),
    path('', include('task.urls')),
    path('', include('wiki.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<slug:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
    path('<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
]

task/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'task'
urlpatterns = [
    path('api/task/state/', apis.set_state, name='state_api'),

    path('user/<str:username>/task/', views.UserTaskView.as_view(), name='user_task'),

    path('<slug:project>/task/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('board/', views.BoardView.as_view(), name='board'),
        path('gantt/', views.GanttView.as_view(), name='gantt'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:number>/', views.DetailView.as_view(), name='detail'),
        path('<int:number>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:number>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

task/models.py
from django.conf import settings
from django.db import models

from home.models import Project


class Task(models.Model):

    TODO = 0
    DOING = 1
    DONE = 2

    STATES = (
        (TODO, '未対応'),
        (DOING, '対応中'),
        (DONE, '完了'),
    )

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='プロジェクト')
    number = models.PositiveIntegerField('番号')
    name = models.CharField('名前', max_length=50)
    description = models.TextField('説明', blank=True)
    scheduled_date_from = models.DateField('予定開始日', blank=True, null=True)
    scheduled_date_to = models.DateField('予定終了日', blank=True, null=True)
    date_from = models.DateField('開始日', blank=True, null=True)
    date_to = models.DateField('終了日', blank=True, null=True)
    state = models.IntegerField('状態', choices=STATES, default=TODO, blank=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='authored_tasks', verbose_name='作成者')
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='assigned_tasks', verbose_name='担当者')

    class Meta:
        verbose_name = 'タスク'
        verbose_name_plural = 'タスク'

        unique_together = ('project', 'number')


class TaskComment(models.Model):

    task = models.ForeignKey(Task, on_delete=models.CASCADE, verbose_name='タスク')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='ユーザー')
    content = models.TextField('内容')
    posted_at = models.DateTimeField('投稿日時', auto_now_add=True)

    def __str__(self):
        return self.user.username + ': ' + self.content

    class Meta:
        verbose_name = 'コメント'
        verbose_name_plural = 'コメント'

chat/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormMixin

from .forms import MessageForm
from .models import Channel, ChannelMembership


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'chat/index.html'
    model = Channel
    paginate_by = 20

    def get_queryset(self):
        return Channel.objects.filter(members=self.request.user).all().order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = [(ch, ch.channelmembership_set.get(user=self.request.user)) for ch in context['object_list']]
        return super().get_context_data(**context)


class ChannelView(UserPassesTestMixin, FormMixin, generic.ListView):
    template_name = 'chat/channel.html'
    paginate_by = 20
    form_class = MessageForm

    def dispatch(self, request, *args, **kwargs):
        self.object = get_object_or_404(Channel, pk=self.kwargs.get('pk'))
        self.kwargs[self.page_kwarg] = kwargs.get(self.page_kwarg) or request.GET.get(self.page_kwarg) or 'last'

        return super().dispatch(request, *args, **kwargs)

    def test_func(self):
        if not self.request.user.is_authenticated:
            return False

        if not self.object.members.filter(pk=self.request.user.pk).exists():
            self.raise_exception = True
            return False
        return True

    def get(self, request, *args, **kwargs):
        membership = self.object.channelmembership_set.get(user=request.user)
        if membership.unread_count > 0:
            membership.unread_count = 0
            membership.save()

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect(self.get_success_url())

    def form_valid(self, form):
        message = form.save(commit=False)
        message.channel = self.object
        message.user = self.request.user
        message.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('chat:channel', args=(self.object.pk,))

    def get_queryset(self):
        return self.object.message_set.all().order_by('posted_at')

    def get_context_data(self, **kwargs):
        context = {
            'channel': self.object
        }
        context.update(kwargs)
        return super().get_context_data(**context)


class NewChannelView(LoginRequiredMixin, FormMixin, generic.DetailView):
    template_name = 'chat/new_channel.html'
    model = get_user_model()
    context_object_name = 'object'
    form_class = MessageForm

    channel = None

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.id == request.user.id:
            return HttpResponseRedirect(reverse('chat:index'))

        channel = Channel.objects.filter_by_members([request.user, self.object]).first()
        if channel:
            return HttpResponseRedirect(reverse('chat:channel', args=(channel.pk,)))

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect(request.build_absolute_uri())

    def form_valid(self, form):
        self.channel = Channel.objects.create()

        ChannelMembership.objects.create(channel=self.channel, user=self.request.user)
        ChannelMembership.objects.create(channel=self.channel, user=self.object)

        message = form.save(commit=False)
        message.channel = self.channel
        message.user = self.request.user
        message.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('chat:channel', args=(self.channel.pk,))

task/views.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Max, Min
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormMixin

from home.mixins import ProjectMixin
from .forms import TaskForm, TaskCommentForm, TaskSearchForm
from .models import Task


class IndexView(ProjectMixin, generic.ListView):
    template_name = 'task/index.html'
    model = Task
    ordering = ('-pk')
    paginate_by = 20

    def get_queryset(self):
        self.form = TaskSearchForm(self.request.GET)
        return self.form.filter_query(super().get_queryset())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context


class BoardView(ProjectMixin, generic.ListView):
    template_name = 'task/board.html'
    model = Task
    ordering = ('-pk')

    def get_context_data(self, **kwargs):
        queryset = self.get_queryset()
        task_list = []
        for i, name in Task.STATES:
            task_list.append((name, queryset.filter(state=i)))

        context = super().get_context_data(**kwargs)
        context['task_list'] = task_list
        return context


class GanttView(ProjectMixin, generic.ListView):
    template_name = 'task/gantt.html'
    model = Task
    ordering = ('pk')
    paginate_by = 20

    @staticmethod
    def daterange(date_from, date_to):
        count = ( date_to - date_from ).days + 1
        return [date_from + datetime.timedelta(days=n) for n in range(count)]

    @staticmethod
    def group_dates_by_month(dates, min_date):
        months = [{'date': min_date, 'start': 0, 'length': 0}]
        for date in dates:
            if months[-1]['date'].month == date.month:
                months[-1]['length'] += 1
            else:
                months.append({'date': date, 'length': 1})
        return months

    @staticmethod
    def get_charts(tasks, min_date):
        for task in tasks:
            chart = dict()
            if task.date_from:
                chart['start'] = (task.date_from - min_date).days
            elif task.date_to:
                chart['start'] = (task.date_to - min_date).days

            if task.date_from and task.date_to:
                chart['length'] = (task.date_to - task.date_from).days
            elif task.date_from or task.date_to:
                chart['length'] = 1

            if task.scheduled_date_from:
                chart['scheduled_start'] = (task.scheduled_date_from - min_date).days
            elif task.scheduled_date_to:
                chart['scheduled_start'] = (task.scheduled_date_to - min_date).days

            if task.scheduled_date_from and task.scheduled_date_to:
                chart['scheduled_length'] = (task.scheduled_date_to - task.scheduled_date_from).days
            elif task.scheduled_date_from or task.scheduled_date_to:
                chart['scheduled_length'] = 1

            yield chart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        q = context['object_list'].aggregate(Min('date_from'), Max('date_to'))
        if not q['date_from__min']:
            q['date_from__min'] = datetime.date.today()
        if not q['date_to__max']:
            q['date_to__max'] = datetime.date.today()

        min_date = q['date_from__min'] - datetime.timedelta(days=7)
        max_date = q['date_to__max'] + datetime.timedelta(days=7)
        dates = self.daterange(min_date, max_date)

        context['today'] = datetime.date.today()
        context['dates'] = dates
        context['months'] = self.group_dates_by_month(dates, min_date)
        context['charts'] = zip(context['object_list'], self.get_charts(context['object_list'], min_date))
        return context


class CreateView(ProjectMixin, generic.CreateView):
    template_name = 'task/create.html'
    form_class = TaskForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def form_valid(self, form):
        q = Task.objects.filter(project=self.project).aggregate(Max('number'))
        if not q['number__max']:
            q['number__max'] = 0

        self.object = form.save(commit=False)
        self.object.project = self.project
        self.object.number = q['number__max'] + 1
        self.object.author = self.request.user
        self.object.save()
        form.save_m2m()

        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('task:detail', args=(self.project.slug, self.object.number,))


class DetailView(ProjectMixin, FormMixin, generic.DetailView):
    template_name = 'task/detail.html'
    model = Task
    form_class = TaskCommentForm

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, number=self.kwargs.get('number'))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect(self.get_success_url())

    def form_valid(self, form):
        task = form.save(commit=False)
        task.task = self.object
        task.user = self.request.user
        task.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('task:detail', args=(self.project.slug, self.object.number,))


class UpdateView(ProjectMixin, generic.UpdateView):
    template_name = 'task/update.html'
    model = Task
    form_class = TaskForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, number=self.kwargs.get('number'))

    def get_success_url(self):
        return reverse('task:detail', args=(self.project.slug, self.object.number,))


class DeleteView(ProjectMixin, generic.DeleteView):
    template_name = 'task/delete.html'
    model = Task

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, number=self.kwargs.get('number'))

    def test_func(self):
        if not super().test_func():
            return False

        self.object = self.get_object()
        if self.object.author != self.request.user:
            self.raise_exception = True
            return False
        return True

    def get_success_url(self):
        return reverse('task:index', args=(self.project.slug,))


class UserTaskView(LoginRequiredMixin, generic.ListView):
    template_name = 'task/user_task.html'
    model = Task
    ordering = ('-pk')
    paginate_by = 20

    def get_queryset(self):
        self.user_object = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))

        query = super().get_queryset().filter(assignees=self.user_object)
        self.state = self.request.GET.get('state', 'undone')
        if self.state == 'undone':
            return query.exclude(state=2)
        elif self.state == 'done':
            return query.filter(state=2)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_object'] = self.user_object
        context['state'] = self.state
        return context

task/templates/task/board.html
{% extends "base_project.html" %}

{% load static %}
{% load bulma %}

{% block title %}タスク{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/task.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'task:index' project.slug %}">タスク</a></li>
      <li class="is-active"><a href="#">ボード</a></li>
    </ul>
  </nav>

  <h2 class="title">タスク</h2>

  <div class="columns is-mobile">
    {% for state_name, tasks in task_list %}
      <div class="column">
        <p>
          <span class="tag is-rounded task-state-tag task-state-{{ forloop.counter0 }}">{{ state_name }}</span>
        </p>
        <div class="task-board" id="task-board{{ forloop.counter0 }}">
          {% for task in tasks %}
            <a href="{% url 'task:detail' project.slug task.number %}" class="task-item is-clearfix" id="task-item{{ task.pk }}">
              <div>
                <div class="task-name">
                  {{ task.name }}
                </div>
              </div>
              <div>
                <span class="task-info">#{{ task.number }} {{ task.author.username }}が作成</span>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj %}
    </nav>
  {% endif %}

  <hr>
{% endblock %}

{% block extra_body %}
<script src="https://cdn.jsdelivr.net/npm/sortablejs@1.6.1/Sortable.min.js"></script>
<script src="https://unpkg.com/axios@0.18.0/dist/axios.min.js"></script>
<script>
  var config = {
    xsrfCookieName: 'csrftoken',
    xsrfHeaderName: 'X-CSRFToken',
  };

  var $list = document.getElementsByClassName('task-board');

  for(var i = 0; i < $list.length; i++){
    Sortable.create($list[i], {
      group: 'task',
      animation: 100,
      ghostClass: 'task-board-ghost',
      onEnd: function (evt) {
        var pk = evt.item.id.slice(9);
        var state = evt.item.parentNode.id.slice(10);

        axios.post('{% url "task:state_api" %}', {pk: pk, state: state}, config);
    	},
    });
  }

</script>
{% endblock %}

task/templates/task/create.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}タスク{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'task:index' project.slug %}">タスク</a></li>
      <li class="is-active"><a href="#">作成</a></li>
    </ul>
  </nav>

  <h2 class="title">タスク作成</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {% bulma_field field %}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="作成">
      </div>
    </div>
  </form>
{% endblock %}

task/templates/task/detail.html
{% extends "base_project.html" %}

{% load humanize static %}
{% load avatar bulma %}

{% block title %}タスク{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/task.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'task:index' project.slug %}">タスク</a></li>
      <li class="is-active"><a href="#">詳細</a></li>
    </ul>
  </nav>

  <h2 class="title">#{{ object.number }} : {{ object.name }}</h2>

  <hr>

  <div class="columns">
    <div class="column is-9">
      {% if object.description %}
      	{{ object.description | linebreaks }}
      {% else %}
      	<p>このタスクの説明はありません。</p>
      {% endif %}

      <p>作成者 : {{ object.author.username }}</p>

      <p>
        <a href="{% url 'task:update' project.slug object.number %}" class="button is-light">編集</a>
        {% if object.author == user %}
          <a href="{% url 'task:delete' project.slug object.number %}" class="button is-light">削除</a>
        {% endif %}
      </p>
    </div>

    <div class="column is-3 task-detail-info">
      <h4>状態</h4>
      <p>
        <span class="tag is-rounded task-state-tag task-state-{{ object.state }}">{{ object.get_state_display }}</span>
      </p>

      <h4>日程</h4>
      <p>
        {% if object.date_from or object.date_to %}
          {{ object.date_from|date }} ～ {{ object.date_to|date }}
        {% else %}
          なし
        {% endif %}
      </p>

      <h4>担当者</h4>
      <p>
        {% for assignee in object.assignees.all %}
          {{ assignee.username }}
        {% empty %}
          まだ担当者がいません。
        {% endfor %}
      </p>
    </div>
  </div>

  <hr>

  <div class="task-comments">
    {% for comment in object.taskcomment_set.all %}
      <div class="media task-comment">
        <figure class="media-left">
          <div class="image is-32x32">
            {% avatar_img comment.user 32 %}
          </div>
        </figure>
        <div class="media-content">
          <div>
            <span class="task-comment-name">{{ comment.user.username }}</span>
            <span class="task-comment-time">{{ comment.posted_at|naturaltime }}</span>
          </div>

          <div class="task-comment-content">
            {{ comment.content|linebreaks }}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <form method="post" autocomplete="off">
    {% csrf_token %}
    <div class="field">
      <div class="control">
        {% bulma_field form.content %}
      </div>
    </div>
    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="送信">
      </div>
    </div>
  </form>
{% endblock %}

task/templates/task/gantt.html
{% extends "base_project.html" %}

{% load static %}
{% load bulma %}

{% block title %}タスク{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/task.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'task:index' project.slug %}">タスク</a></li>
      <li class="is-active"><a href="#">ガントチャート</a></li>
    </ul>
  </nav>

  <h2 class="title">ガントチャート</h2>

  <hr>

  <div class="tags has-addons is-small is-pulled-right">
    <span class="tag task-state-0">未対応</span>
    <span class="tag task-state-1">対応中</span>
    <span class="tag task-state-2">完了</span>
  </div>

  <div class="task-gantt">
    <div class="task-gantt-items">
      <div class="task-gantt-row"></div>
      <div class="task-gantt-row">タスク</div>
      {% for task in object_list %}
        <div class="task-gantt-row">
          <a href="{% url 'task:detail' project.slug task.number %}">
            #{{ task.number }} : {{ task.name }}
          </a>
        </div>
      {% endfor %}
    </div>
    <div class="task-gantt-charts">
      <div class="task-gantt-charts-wrapper" style="width:{{dates|length}}rem;">
        <div class="task-gantt-row">
          {% for month in months %}
            <div class="task-gantt-cell task-gantt-month" style="width:{{ month.length }}rem;">
              {% if month.length >= 5 %}
                {{ month.date|date:"Y年n月" }}
              {% elif month.length >= 2 %}
                {{ month.date|date:"n月" }}
              {% endif %}
            </div>
          {% endfor %}
        </div>
        <div class="task-gantt-row">
          {% for date in dates %}
            <div class="task-gantt-cell task-gantt-date task-gantt-day{{ date.weekday }} {% if date == today %}task-gantt-today{% endif %}">
              {{ date|date:"j" }}
            </div>
          {% endfor %}
        </div>
        {% for task, chart in charts %}
          <div class="task-gantt-row">
            {% for date in dates %}
              <div class="task-gantt-cell task-gantt-day{{ date.weekday }} {% if date == today %}task-gantt-today{% endif %}">
              </div>
            {% endfor %}

            {% if chart.scheduled_start %}
              <div class="task-gantt-subbar task-state-{{ task.state }}-dark" style="left:{{ chart.scheduled_start }}rem; width:{{ chart.scheduled_length }}rem;"></div>
            {% endif %}
            {% if chart.start %}
              <div class="task-gantt-bar task-state-{{ task.state }}" style="left:{{ chart.start }}rem; width:{{ chart.length }}rem;"></div>
            {% endif %}

          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <hr>

  <p>
    <a href="{% url 'task:create' project.slug %}">タスクを作成する</a>
  </p>

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj %}
    </nav>
  {% endif %}
{% endblock %}

task/templates/task/index.html
{% extends "base_project.html" %}

{% load static %}
{% load bulma utils %}

{% block title %}タスク{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/task.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">タスク</a></li>
    </ul>
  </nav>

  <h2 class="title">タスク</h2>

  <div class="tabs">
    <ul>
      <li class="{% if form.state.value != 'done' %}is-active{% endif %}">
        <a href="{% if form.state.value != 'done' %}#{% else %}{% urlparams request.GET state='undone' page=None %}{% endif %}">未完了</a>
      </li>
      <li class="{% if form.state.value == 'done' %}is-active{% endif %}">
        <a href="{% if form.state.value == 'done' %}#{% else %}{% urlparams request.GET state='done' page=None %}{% endif %}">完了</a>
      </li>
      <li class="tab-spacer"></li>
      <li>
        <form>
          {% if form.state.value %}{{ form.state }}{% endif %}

          <div class="control has-icons-left">
            {% bulma_field form.keyword %}
            <span class="icon is-small is-left is-marginless">
              <i class="fa fa-search"></i>
            </span>
          </div>
        </form>
      </li>
    </ul>
  </div>

  {% for task in object_list %}
    <a href="{% url 'task:detail' project.slug task.number %}" class="task-item is-clearfix">
      <div>
        <div class="task-name">
          {{ task.name }}
        </div>
      </div>
      <div>
        {% if state != 'done' %}
          <span class="tag is-rounded task-state-tag task-state-{{ task.state }}">{{ task.get_state_display }}</span>
        {% endif %}
        <span class="task-info">#{{ task.number }} {{ task.author.username }}が作成</span>
      </div>
    </a>
  {% empty %}
    <p>
      まだタスクがありません。
    </p>
  {% endfor %}

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj extra=request.GET %}
    </nav>
  {% endif %}

  <hr>

  <p>
    <a href="{% url 'task:create' project.slug %}">タスクを作成する</a> /
    <a href="{% url 'task:gantt' project.slug %}">ガントチャート</a> /
    <a href="{% url 'task:board' project.slug %}">ボード</a>
  </p>
{% endblock %}