account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user/', views.UserView.as_view(), name='user'),
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('user/<str:slug>/', views.UserDetailView.as_view(), name='user_detail'),
]

chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ChannelView.as_view(), name='channel'),
    path('new/<int:pk>/', views.NewChannelView.as_view(), name='new_channel'),
]

elcats/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chat/', include('chat.urls')),

    path('', include('account.urls')),
    path('', include('schedule.urls')),
    path('', include('task.urls')),
    path('', include('wiki.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<slug:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
    path('<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
]

schedule/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'schedule'
urlpatterns = [
    path('api/schedule/participate/', apis.set_participant, name='participant_api'),

    path('user/<str:username>/schedule/', views.UserScheduleView.as_view(), name='user_schedule'),

    path('<slug:project>/schedule/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('week/', views.WeekView.as_view(), name='week'),
        path('week/<int:year>-<int:month>-<int:day>/', views.WeekView.as_view(), name='week'),
        path('month/', views.MonthView.as_view(), name='month'),
        path('month/<int:year>-<int:month>/', views.MonthView.as_view(), name='month'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

task/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'task'
urlpatterns = [
    path('api/task/state/', apis.set_state, name='state_api'),

    path('user/<str:username>/task/', views.UserTaskView.as_view(), name='user_task'),

    path('<slug:project>/task/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('board/', views.BoardView.as_view(), name='board'),
        path('gantt/', views.GanttView.as_view(), name='gantt'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:number>/', views.DetailView.as_view(), name='detail'),
        path('<int:number>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:number>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

wiki/urls.py
from django.urls import include, path

from . import views


app_name = 'wiki'
urlpatterns = [
    path('<slug:project>/wiki/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
        path('<slug:slug>/update/', views.UpdateView.as_view(), name='update'),
        path('<slug:slug>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

home/models.py
from django.conf import settings
from django.core.validators import ValidationError
from django.db import models


class Project(models.Model):

    name = models.CharField('名前', max_length=50)
    slug = models.SlugField('スラッグ', max_length=50, unique=True)
    description = models.CharField('説明', max_length=50, blank=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='メンバー')
    is_private = models.BooleanField('非公開', default=False)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)

    def clean(self):
        if self.slug in ('login','logout','password','user','create','admin','api'):
            raise ValidationError({'slug': 'このスラッグは利用できません。'})

    class Meta:
        verbose_name = 'プロジェクト'
        verbose_name_plural = 'プロジェクト'

home/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'slug', 'description', 'members', 'is_private')
        widgets = {
            'members': forms.CheckboxSelectMultiple,
        }
        help_texts = {
            'slug': 'URLなどに使われ、半角の英数字、アンダースコア、ハイフンのみ使用できます。',
            'is_private': 'このプロジェクトの内容をメンバー以外に非公開にします。',
        }

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import ProjectForm
from .mixins import ProjectAccessMixin
from .models import Project


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'home/index.html'
    model = Project
    ordering = ('pk')
    paginate_by = 20

    def get_queryset(self):
        query = super().get_queryset()
        self.type = self.request.GET.get('type', 'mine')
        if self.type == 'mine':
            return query.filter(members=self.request.user)
        elif self.type == 'all':
            return query.filter(Q(is_private=False) | Q(members=self.request.user)).distinct()
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = self.type
        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'home/project_create.html'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('home:project_detail', args=(self.object.slug,))


class ProjectDetailView(ProjectAccessMixin, generic.DetailView):
    template_name = 'home/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectSettingsView(ProjectAccessMixin, generic.UpdateView):
    template_name = 'home/project_settings.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('home:project_detail', args=(self.object.slug,))


class ProjectDeleteView(ProjectAccessMixin, generic.DeleteView):
    template_name = 'home/project_delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('home:project_list')

home/templates/base.html
{% load static avatar %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <title>{% block title %}{% endblock %} ｜ Elcats</title>
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/icon32.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/icon180.png' %}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  {% block extra_head %}{% endblock %}
</head>
<body>
  <header class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>

        <a class="navbar-item navbar-logo" href="/"><img src="{% static 'img/logo.png' %}" alt="Elcats"/></a>
      </div>
      <div class="navbar-menu">
        <div class="navbar-end">
          {% if user.is_authenticated %}
            <div class="navbar-item is-hidden-mobile-xs">
              <div class="buttons">
                <a class="button is-light" href="{% url 'task:user_task' user.username %}">
                  <i class="fa fa-tasks" aria-hidden="true"></i>
                </a>
                <a class="button is-light" href="{% url 'schedule:user_schedule' user.username %}">
                  <i class="fa fa-calendar" aria-hidden="true"></i>
                </a>
              </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link is-arrowless">
                {% avatar_img user 28 %}
              </a>

              <div class="navbar-dropdown is-right">
                <a class="navbar-item" href="{% url 'account:user_detail' user.username %}">
                  マイページ
                </a>
                <a class="navbar-item" href="{% url 'account:logout' %}">
                  ログアウト
                </a>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
  </header>

  <section class="section">
    {% block main %}
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
  </section>

  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>&copy; 2018 Elcats</p>
      </div>
    </div>
  </footer>

  <div id="sidemenu-back" class="is-hidden"></div>

  <div class="notification is-primary" id="toast">
    <button class="delete" id="toast-delete"></button>
    <div id="toast-content">
    </div>
  </div>

  {% block extra_body %}{% endblock %}
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    var $navbarBurger = document.querySelector('.navbar-burger');
    var $sidebarMenu = document.querySelector('.sidemenu');
    var $sidebarMenuBack = document.getElementById('sidemenu-back');
    if($sidebarMenu){
      $navbarBurger.addEventListener('click', function () {
        $navbarBurger.classList.toggle('is-active');
        $sidebarMenu.classList.toggle('is-active');
        $sidebarMenuBack.classList.toggle('is-hidden');
      });
      $sidebarMenuBack.addEventListener('click', function () {
        $navbarBurger.classList.toggle('is-active');
        $sidebarMenu.classList.toggle('is-active');
        $sidebarMenuBack.classList.toggle('is-hidden');
      });
    }else{
      $navbarBurger.classList.add('is-hidden');
      $sidebarMenuBack.classList.add('is-hidden');
    }

    document.getElementById('toast-delete').addEventListener('click', function () {
      var $toast = document.getElementById('toast');
      $toast.classList.remove('is-active');
      $toast.classList.remove('is-activated');
    })
  });

  function toast(msg) {
    var $toast = document.getElementById('toast');
    $toast.children[1].innerHTML = msg;
    $toast.classList.add('is-activated');

    window.setTimeout(function() {
      $toast.classList.add('is-active');
    }, 100);
    window.setTimeout(function() {
      $toast.classList.remove('is-active');
    }, 3000);
    window.setTimeout(function() {
      $toast.classList.remove('is-activated');
    }, 3500);
  }
  </script>
</body>
</html>

home/templates/base_project.html
{% extends "base_sidemenu.html" %}

{% block sidemenu %}
{% with namespace=request.resolver_match.namespace %}
  <aside class="menu">
    <ul class="menu-list">
      <li>
        <a href="{% url 'home:project_detail' project.slug %}">
          <i class="fa fa-flag" aria-hidden="true"></i> ホーム
        </a>
      </li>
      <li>
        <a href="{% url 'task:index' project.slug %}">
          <i class="fa fa-tasks" aria-hidden="true"></i> タスク
        </a>
        <ul {% if namespace == 'task' %}class="is-active"{% endif %}>
          <li><a href="{% url 'task:index' project.slug %}">一覧</a></li>
          <li><a href="{% url 'task:create' project.slug %}">追加</a></li>
          <li><a href="{% url 'task:board' project.slug %}">ボード</a></li>
          <li><a href="{% url 'task:gantt' project.slug %}">ガントチャート</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'schedule:index' project.slug %}">
          <i class="fa fa-calendar" aria-hidden="true"></i> 予定
        </a>
        <ul {% if namespace == 'schedule' %}class="is-active"{% endif %}>
          <li><a href="{% url 'schedule:index' project.slug %}">一覧</a></li>
          <li><a href="{% url 'schedule:create' project.slug %}">追加</a></li>
          <li><a href="{% url 'schedule:month' project.slug %}">月間</a></li>
          <li><a href="{% url 'schedule:week' project.slug %}">週間</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'wiki:index' project.slug %}">
          <i class="fa fa-book" aria-hidden="true"></i> Wiki
        </a>
        <ul {% if namespace == 'wiki' %}class="is-active"{% endif %}>
          <li><a href="{% url 'wiki:index' project.slug %}">一覧</a></li>
          <li><a href="{% url 'wiki:create' project.slug %}">追加</a></li>
        </ul>
      </li>
      {% comment %}
        <li>
          <a href="{% url 'chat:index' %}">
            <i class="fa fa-comment-o" aria-hidden="true"></i> チャット
          </a>
        </li>
      {% endcomment %}
      <li>
        <a href="#" class="has-text-grey-light">
          <i class="fa fa-folder-open-o" aria-hidden="true"></i> ファイル
        </a>
      </li>
      <li>
        <a href="#" class="has-text-grey-light">
          <i class="fa fa-code-fork" aria-hidden="true"></i> コード
        </a>
      </li>
      <li>
        <a href="{% url 'home:project_settings' project.slug %}">
          <i class="fa fa-cog" aria-hidden="true"></i> 設定
        </a>
      </li>
    </ul>
  </aside>
{% endwith %}
{% endblock %}

home/templates/base_sidemenu.html
{% extends "base.html" %}

{% block main %}
  <div class="columns">
    <div class="column is-2 sidemenu">
      {% block sidemenu %}{% endblock %}
    </div>
    <div class="column is-10">
      <div class="container is-fullhd">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}