account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user/', views.UserView.as_view(), name='user'),
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('user/<str:slug>/', views.UserDetailView.as_view(), name='user_detail'),
]

chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ChannelView.as_view(), name='channel'),
    path('new/<int:pk>/', views.NewChannelView.as_view(), name='new_channel'),
]

elcats/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chat/', include('chat.urls')),

    path('', include('account.urls')),
    path('', include('schedule.urls')),
    path('', include('task.urls')),
    path('', include('wiki.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<slug:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
    path('<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
]

schedule/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'schedule'
urlpatterns = [
    path('api/schedule/participate/', apis.set_participant, name='participant_api'),

    path('user/<str:username>/schedule/', views.UserScheduleView.as_view(), name='user_schedule'),

    path('<slug:project>/schedule/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('week/', views.WeekView.as_view(), name='week'),
        path('week/<int:year>-<int:month>-<int:day>/', views.WeekView.as_view(), name='week'),
        path('month/', views.MonthView.as_view(), name='month'),
        path('month/<int:year>-<int:month>/', views.MonthView.as_view(), name='month'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

task/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'task'
urlpatterns = [
    path('api/task/state/', apis.set_state, name='state_api'),

    path('user/<str:username>/task/', views.UserTaskView.as_view(), name='user_task'),

    path('<slug:project>/task/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('board/', views.BoardView.as_view(), name='board'),
        path('gantt/', views.GanttView.as_view(), name='gantt'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:number>/', views.DetailView.as_view(), name='detail'),
        path('<int:number>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:number>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

wiki/urls.py
from django.urls import include, path

from . import views


app_name = 'wiki'
urlpatterns = [
    path('<slug:project>/wiki/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
        path('<slug:slug>/update/', views.UpdateView.as_view(), name='update'),
        path('<slug:slug>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

home/models.py
from django.conf import settings
from django.core.validators import ValidationError
from django.db import models


class Project(models.Model):

    name = models.CharField('名前', max_length=50)
    slug = models.SlugField('スラッグ', max_length=50, unique=True)
    description = models.CharField('説明', max_length=50, blank=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='メンバー')
    is_private = models.BooleanField('非公開', default=False)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)

    def clean(self):
        if self.slug in ('login','logout','password','user','create','admin','api'):
            raise ValidationError({'slug': 'このスラッグは利用できません。'})

    class Meta:
        verbose_name = 'プロジェクト'
        verbose_name_plural = 'プロジェクト'

home/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('name', 'slug', 'description', 'members', 'is_private')
        widgets = {
            'members': forms.CheckboxSelectMultiple,
        }
        help_texts = {
            'slug': 'URLなどに使われ、半角の英数字、アンダースコア、ハイフンのみ使用できます。',
            'is_private': 'このプロジェクトの内容をメンバー以外に非公開にします。',
        }

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import ProjectForm
from .mixins import ProjectAccessMixin
from .models import Project


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'home/index.html'
    model = Project
    ordering = ('pk')
    paginate_by = 20

    def get_queryset(self):
        query = super().get_queryset()
        self.type = self.request.GET.get('type', 'mine')
        if self.type == 'mine':
            return query.filter(members=self.request.user)
        elif self.type == 'all':
            return query.filter(Q(is_private=False) | Q(members=self.request.user)).distinct()
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = self.type
        return context


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'home/project_create.html'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('home:project_detail', args=(self.object.slug,))


class ProjectDetailView(ProjectAccessMixin, generic.DetailView):
    template_name = 'home/project_detail.html'
    model = Project
    context_object_name = 'project'


class ProjectSettingsView(ProjectAccessMixin, generic.UpdateView):
    template_name = 'home/project_settings.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('home:project_detail', args=(self.object.slug,))


class ProjectDeleteView(ProjectAccessMixin, generic.DeleteView):
    template_name = 'home/project_delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('home:project_list')

home/templates/home/index.html
{% extends "base.html" %}

{% load bulma %}

{% block title %}ホーム{% endblock %}

{% block content %}
  <h2 class="title">プロジェクト一覧</h2>

  <div class="tabs">
    <ul>
      <li class="{% if type == 'mine' %}is-active{% endif %}">
        <a href="{% if type == 'mine' %}#{% else %}?type=mine{% endif %}">参加中</a>
      </li>
      <li class="{% if type == 'all' %}is-active{% endif %}">
        <a href="{% if type == 'all' %}#{% else %}?type=all{% endif %}">すべて</a>
      </li>
    </ul>
  </div>

  {% for project in object_list %}
    <a href="{% url 'home:project_detail' project.slug %}">
      <div>
        {{ project.name }}
      </div>
    </a>
  {% empty %}
    <p>
      まだプロジェクトがありません。
    </p>
  {% endfor %}

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj extra=request.GET %}
    </nav>
  {% endif %}

  <hr>

  <p>
    <a href="{% url 'home:project_create' %}">プロジェクトを作成する</a>
  </p>
{% endblock %}

home/templates/home/login.html
{% extends "base.html" %}
{% load bulma %}

{% block title %}ログイン{% endblock %}

{% block content %}
  <h2 class="title">
    ログイン
  </h2>
  <form action="" method="POST">
    <input type="hidden" name="next" value="{{ next }}" />
    {% csrf_token %}

    {% for field in form %}
      <div class="field">
        <label class="label">{{ field.label }}</label>
        <div class="control">
          {{ field | bulma_form }}
        </div>
        {% for error in field.errors %}
          <p class="help is-danger">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    <hr>

    <div class="field is-grouped">
      <div class="control">
        <button type="submit" class="button is-link">ログイン</button>
      </div>
      <div class="control">
        <a href="{% url 'home:password_reset' %}" class="button is-text">パスワードをお忘れですか？</a>
      </div>
    </div>
  </form>
{% endblock %}

home/templates/home/logout.html
{% extends "base.html" %}

{% block title %}ログアウト{% endblock %}

{% block content %}
  <h2 class="title">
    ログアウトしました
  </h2>
  <p>
    <a href="{% url 'home:index' %}">ログイン</a>
  </p>
{% endblock %}

home/templates/home/project_create.html
{% extends "base.html" %}

{% load bulma %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li class="is-active"><a href="#">プロジェクト作成</a></li>
    </ul>
  </nav>

  <h2 class="title">プロジェクト作成</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {% bulma_field field %}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% empty %}
            {% if field.help_text %}<p class="help">{{ field.help_text }}</p>{% endif %}
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="作成">
      </div>
    </div>
  </form>
{% endblock %}

home/templates/home/project_delete.html
{% extends "base_project.html" %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">削除</a></li>
    </ul>
  </nav>

  <h2 class="title">プロジェクト削除</h2>
  <h3 class="subtitle">{{ project.name }}</h3>

  <hr>

  <p>
    プロジェクト「{{ project.name }}」を削除していいですか？<br>
    この操作は元に戻せません。
  </p>

  <form method="post">
    {% csrf_token %}

    <div class="field is-grouped">
      <div class="control">
        <input class="button is-danger" type="submit" value="削除">
      </div>
      <div class="control">
        <a href="{% url 'home:project_detail' project.slug %}" class="button is-text">戻る</a>
      </div>
    </div>
  </form>
{% endblock %}

home/templates/home/project_detail.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li class="is-active"><a href="#">{{ project.name }}</a></li>
    </ul>
  </nav>

  <h2 class="title">{{ project.name }}</h2>

  <p>
  	{{ project.description }}
  </p>

  <hr>

  <p>
    <a href="{% url 'task:index' project.slug %}">タスク</a> /
    <a href="{% url 'schedule:index' project.slug %}">予定</a> /
    <a href="{% url 'wiki:index' project.slug %}">Wiki</a>
    {% comment %}<a href="{% url 'chat:index' %}">チャット</a>{% endcomment %}
  </p>
{% endblock %}

home/templates/home/project_setting.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">設定</a></li>
    </ul>
  </nav>

  <h2 class="title">プロジェクト設定</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {{ field | bulma_form }}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% empty %}
            {% if field.help_text %}<p class="help">{{ field.help_text }}</p>{% endif %}
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field is-grouped">
      <div class="control is-expanded">
        <input class="button is-primary" type="submit" value="更新">
      </div>
      <div class="control">
        <a href="{% url 'home:project_delete' project.slug %}" class="button is-danger">削除</a>
      </div>
    </div>
  </form>

{% endblock %}

home/templates/home/project_settings.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">設定</a></li>
    </ul>
  </nav>

  <h2 class="title">プロジェクト設定</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {% bulma_field field %}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% empty %}
            {% if field.help_text %}<p class="help">{{ field.help_text }}</p>{% endif %}
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field is-grouped">
      <div class="control is-expanded">
        <input class="button is-primary" type="submit" value="更新">
      </div>
      <div class="control">
        <a href="{% url 'home:project_delete' project.slug %}" class="button is-danger">削除</a>
      </div>
    </div>
  </form>

{% endblock %}

home/templates/home/project_update.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}プロジェクト{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">編集</a></li>
    </ul>
  </nav>

  <h2 class="title">プロジェクト編集</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {{ field | bulma_form }}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="更新">
      </div>
    </div>
  </form>
{% endblock %}

home/templates/home/user.html
{% extends "base.html" %}

{% load bulma %}

{% block title %}ユーザーを探す{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li class="is-active"><a href="#">ユーザー一覧</a></li>
    </ul>
  </nav>

  <h2 class="title">ユーザーを探す</h2>

  {% for u in object_list %}
    <p><a href="{% url 'home:user_detail' u.username %}">{{ u.username }}</a></p>
  {% empty %}
    <p>まだユーザーがいません。</p>
  {% endfor %}

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj %}
    </nav>
  {% endif %}
{% endblock %}

home/templates/home/user_detail.html
{% extends "base.html" %}

{% load avatar %}

{% block title %}{{ object.username }}{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li class="is-active"><a href="#">ユーザー詳細</a></li>
    </ul>
  </nav>

  <div class="media">
    <figure class="media-left">
      <p class="image is-64x64">
        {% avatar_img object 64 %}
      </p>
    </figure>
    <div class="media-content">
      <h2 class="title is-clearfix">{{ object.username }}</h2>
    </div>
  </div>

  <p>
    <a href="{% url 'chat:new_channel' object.pk %}">チャット</a>
    {% if user == object %}
      <a href="{% url 'home:password_change' %}">パスワード変更</a>
    {% endif %}
  </p>
{% endblock %}