account/urls.py
from django.urls import path

from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('user/', views.UserView.as_view(), name='user'),
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('user/<str:slug>/', views.UserDetailView.as_view(), name='user_detail'),
]

chat/urls.py
from django.urls import path

from . import views


app_name = 'chat'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ChannelView.as_view(), name='channel'),
    path('new/<int:pk>/', views.NewChannelView.as_view(), name='new_channel'),
]

elcats/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('chat/', include('chat.urls')),

    path('', include('account.urls')),
    path('', include('schedule.urls')),
    path('', include('task.urls')),
    path('', include('wiki.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path

from . import views


app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<slug:slug>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<slug:slug>/settings/', views.ProjectSettingsView.as_view(), name='project_settings'),
    path('<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
]

schedule/urls.py
from django.urls import include, path

from . import apis, views


app_name = 'schedule'
urlpatterns = [
    path('api/schedule/participate/', apis.set_participant, name='participant_api'),

    path('user/<str:username>/schedule/', views.UserScheduleView.as_view(), name='user_schedule'),

    path('<slug:project>/schedule/', include([
        path('', views.IndexView.as_view(), name='index'),
        path('week/', views.WeekView.as_view(), name='week'),
        path('week/<int:year>-<int:month>-<int:day>/', views.WeekView.as_view(), name='week'),
        path('month/', views.MonthView.as_view(), name='month'),
        path('month/<int:year>-<int:month>/', views.MonthView.as_view(), name='month'),
        path('create/', views.CreateView.as_view(), name='create'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    ])),
]

schedule/models.py
from django.conf import settings
from django.db import models

from recurrence.fields import RecurrenceField

from home.models import Project


class Schedule(models.Model):

    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='プロジェクト')
    name = models.CharField('名前', max_length=50)
    description = models.TextField('説明', blank=True)
    place = models.CharField('場所', max_length=50, blank=True)
    date = models.DateField('日付')
    time_from = models.TimeField('開始時間', blank=True, null=True)
    time_to = models.TimeField('終了時間', blank=True, null=True)
    recurrence = RecurrenceField(include_dtstart=False, blank=True, verbose_name='繰り返し条件')
    recur_until = models.DateField('繰り返し終了日', blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='authored_schedules', verbose_name='作成者')
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='participated_schedules', verbose_name='参加者')

    def get_occurence_dates(self, start, end):
        if start < self.date:
            start = self.date
        if self.recur_until < end:
            end = self.recur_until
        if end < start:
            return []

        return self.recurrence.between(start, end, dtstart=start, inc=True)

    class Meta:
        verbose_name = '予定'
        verbose_name_plural = '予定'


class ScheduleOccurence(models.Model):

    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, verbose_name='予定')
    date = models.DateField('日付')

    class Meta:
        verbose_name = '実予定'
        verbose_name_plural = '実予定'


class ScheduleComment(models.Model):

    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, verbose_name='予定')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='ユーザー')
    content = models.TextField('内容')
    posted_at = models.DateTimeField('投稿日時', auto_now_add=True)

    def __str__(self):
        return self.user.username + ': ' + self.content

    class Meta:
        verbose_name = 'コメント'
        verbose_name_plural = 'コメント'

schedule/forms.py
from django import forms
from django.db.models import Q

from .models import Schedule, ScheduleComment


class ScheduleSearchForm(forms.Form):
    keyword = forms.CharField(label='', max_length=500, required=False)
    type = forms.CharField(label='', max_length=20, required=False, widget=forms.HiddenInput)

    def filter_query(self, query, user):
        if not self.is_valid():
            return query

        type = self.cleaned_data['type']
        if type != 'all':
            query = query.filter(participants=user)

        keyword = self.cleaned_data['keyword'].strip()
        if keyword:
            for w in keyword.split():
                query = query.filter(Q(name__contains=w) | Q(description__contains=w))

        return query


class ScheduleForm(forms.ModelForm):

    def __init__(self, project=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if project:
            self.fields['participants'].queryset = project.members.all()

    class Meta:
        model = Schedule
        exclude = ('project', 'author', 'recurrence', 'recur_until')
        widgets = {
            'date': forms.DateInput(attrs={"type": "date"}),
            'participants': forms.CheckboxSelectMultiple,
        }


class ScheduleCommentForm(forms.ModelForm):

    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "コメントを入力", 'rows': 5}), label="")

    class Meta:
        model = ScheduleComment
        fields = ('content',)

schedule/views.py
import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormMixin

from home.mixins import ProjectMixin
from .forms import ScheduleForm, ScheduleCommentForm, ScheduleSearchForm
from .mixins import MonthCalendarMixin, WeekCalendarMixin
from .models import Schedule


class IndexView(ProjectMixin, generic.ListView):
    template_name = 'schedule/index.html'
    model = Schedule
    ordering = ('date', 'time_from')
    paginate_by = 20

    def get_queryset(self):
        self.form = ScheduleSearchForm(self.request.GET)
        return self.form.filter_query(super().get_queryset(), self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form
        return context


class BaseCalendarView(ProjectMixin, generic.ListView):
    model = Schedule
    ordering = ('date', 'time_from')

    def get_date_schedule_dict(self, dates):
        """ ソート済みのdatetime型リストをキーとしたリストの辞書を返す """
        data = { d: [] for d in dates }
        schedules = self.get_queryset().filter(date__range=(dates[0], dates[-1])).iterator()
        schedule = next(schedules, None)

        for day, list in data.items():
            if not schedule:
                break
            if day < schedule.date:
                continue
            while schedule and day == schedule.date:
                list.append(schedule)
                schedule = next(schedules, None)
        return data


class WeekView(WeekCalendarMixin, BaseCalendarView):
    template_name = 'schedule/week.html'

    def get_week_calendar(self):
        data = super().get_week_calendar()
        data['date_list'] = self.get_date_schedule_dict(data['days'])
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['calendar'] = self.get_week_calendar()
        return context


class MonthView(MonthCalendarMixin, BaseCalendarView):
    template_name = 'schedule/month.html'

    def get_month_calendar(self):
        data = super().get_month_calendar()
        data['date_list'] = self.get_date_schedule_dict(data['days'])
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['calendar'] = self.get_month_calendar()
        return context


class CreateView(ProjectMixin, generic.CreateView):
    template_name = 'schedule/create.html'
    form_class = ScheduleForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.project = self.project
        self.object.author = self.request.user
        self.object.save()
        form.save_m2m()

        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('schedule:detail', args=(self.project.slug, self.object.pk,))


class DetailView(ProjectMixin, FormMixin, generic.DetailView):
    template_name = 'schedule/detail.html'
    model = Schedule
    form_class = ScheduleCommentForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return redirect(self.get_success_url())

    def form_valid(self, form):
        task = form.save(commit=False)
        task.schedule = self.object
        task.user = self.request.user
        task.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('schedule:detail', args=(self.project.slug, self.object.pk,))


class UpdateView(ProjectMixin, generic.UpdateView):
    template_name = 'schedule/update.html'
    model = Schedule
    form_class = ScheduleForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs

    def test_func(self):
        if not super().test_func():
            return False

        self.object = self.get_object()
        if self.object.author != self.request.user:
            self.raise_exception = True
            return False
        return True

    def get_success_url(self):
        return reverse('schedule:detail', args=(self.project.slug, self.object.pk,))


class DeleteView(ProjectMixin, generic.DeleteView):
    template_name = 'schedule/delete.html'
    model = Schedule

    def test_func(self):
        if not super().test_func():
            return False

        self.object = self.get_object()
        if self.object.author != self.request.user:
            self.raise_exception = True
            return False
        return True

    def get_success_url(self):
        return reverse('schedule:index', args=(self.project.slug,))


class UserScheduleView(LoginRequiredMixin, generic.ListView):
    template_name = 'schedule/user_schedule.html'
    model = Schedule
    ordering = ('date', 'time_from')
    paginate_by = 20

    def get_queryset(self):
        self.user_object = get_object_or_404(get_user_model(), username=self.kwargs.get('username'))
        query = super().get_queryset().filter(participants=self.user_object)
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_object'] = self.user_object
        return context

schedule/templates/schedule/create.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}予定{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li class="is-active"><a href="#">作成</a></li>
    </ul>
  </nav>

  <h2 class="title">予定作成</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {% bulma_field field %}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="作成">
      </div>
    </div>
  </form>
{% endblock %}

schedule/templates/schedule/delete.html
{% extends "base_project.html" %}

{% block title %}予定{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li><a href="{% url 'schedule:detail' project.slug object.pk %}">詳細</a></li>
      <li class="is-active"><a href="#">削除</a></li>
    </ul>
  </nav>

  <h2 class="title">予定削除</h2>
  <h3 class="subtitle">{{ object.name }}</h3>

  <hr>

  <p>予定「{{ object.name }}」を削除していいですか？</p>

  <form method="post">
    {% csrf_token %}

    <div class="field is-grouped">
      <div class="control">
        <input class="button is-danger" type="submit" value="削除">
      </div>
      <div class="control">
        <a href="{% url 'schedule:detail' project.slug object.pk %}" class="button is-text">戻る</a>
      </div>
    </div>
  </form>
{% endblock %}

schedule/templates/schedule/detail.html
{% extends "base_project.html" %}

{% load humanize static %}
{% load avatar bulma %}

{% block title %}予定{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/schedule.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li class="is-active"><a href="#">詳細</a></li>
    </ul>
  </nav>

  <h2 class="title">{{ object.name }}</h2>

  <hr>

  <div class="columns">
    <div class="column is-9">
      {% if object.description %}
      	{{ object.description | linebreaks }}
      {% else %}
      	<p>この予定の説明はありません。</p>
      {% endif %}

      <p>作成者 : {{ object.author.username }}</p>

      <p>
        <button type="button" id="participate-button" class="button is-light">
          {% if user not in object.participants.all %}
            参加する
          {% else %}
            予定を外す
          {% endif %}
        </button>

        {% if object.author == user %}
          <a href="{% url 'schedule:update' project.slug object.pk %}" class="button is-light">編集</a>
          <a href="{% url 'schedule:delete' project.slug object.pk %}" class="button is-light">削除</a>
        {% endif %}
      </p>
    </div>

    <div class="column is-3 schedule-detail-info">
      <h4>日時</h4>
      <p>
        {{ object.date|date }}<br>
        {% if object.time_from %}
          {{ object.time_from|time:"H:i" }} ～
          {% if object.time_to %}{{ object.time_to|time:"H:i" }}{% endif %}
        {% endif %}
      </p>

      {% if object.place %}
        <h4>場所</h4>
        <p>{{ object.place }}</p>
      {% endif %}

      <h4>参加者</h4>
      <p>
        {% for participant in object.participants.all %}
          {{ participant.username }}
        {% empty %}
          まだ参加者がいません。
        {% endfor %}
      </p>
    </div>
  </div>

  <hr>

  <div class="schedule-comments">
    {% for comment in object.schedulecomment_set.all %}
      <div class="media schedule-comment">
        <figure class="media-left">
          <div class="image is-32x32">
            {% avatar_img comment.user 32 %}
          </div>
        </figure>
        <div class="media-content">
          <div>
            <span class="schedule-comment-name">{{ comment.user.username }}</span>
            <span class="schedule-comment-time">{{ comment.posted_at|naturaltime }}</span>
          </div>

          <div class="schedule-comment-content">
            {{ comment.content|linebreaks }}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <form method="post" autocomplete="off">
    {% csrf_token %}
    <div class="field">
      <div class="control">
        {% bulma_field form.content %}
      </div>
    </div>
    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="送信">
      </div>
    </div>
  </form>
{% endblock %}

{% block extra_body %}
<script src="https://unpkg.com/axios@0.18.0/dist/axios.min.js"></script>
<script>
  var config = {
    xsrfCookieName: 'csrftoken',
    xsrfHeaderName: 'X-CSRFToken',
  };

  var pk = {{ object.pk }};
  var isParticipated = {% if user in object.participants.all %}true{% else %}false{% endif %};

  document.addEventListener('DOMContentLoaded', function () {
    var $participateButton = document.getElementById('participate-button')
    $participateButton.addEventListener('click', function () {
      var action = (!isParticipated) ? 'add' : 'remove';

      axios.post(
        '{% url "schedule:participant_api" %}', {pk: pk, action: action}, config
      ).then(function (res) {
        isParticipated = !isParticipated;
        $participateButton.innerHTML = (!isParticipated) ? '参加する' : '予定を外す';
      });
    });
  });
</script>
{% endblock %}

schedule/templates/schedule/index.html
{% extends "base_project.html" %}

{% load humanize static %}
{% load bulma utils %}

{% block title %}予定{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/schedule.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li class="is-active"><a href="#">予定</a></li>
    </ul>
  </nav>

  <h2 class="title">予定</h2>

  <div class="tabs">
    <ul>
      <li class="{% if form.type.value != 'all' %}is-active{% endif %}">
        <a href="{% if form.type.value != 'all' %}#{% else %}{% urlparams request.GET type='participated' page=None %}{% endif %}">参加中</a>
      </li>
      <li class="{% if form.type.value == 'all' %}is-active{% endif %}">
        <a href="{% if form.type.value == 'all' %}#{% else %}{% urlparams request.GET type='all' page=None %}{% endif %}">すべて</a>
      </li>
      <li class="tab-spacer"></li>
      <li>
        <form>
          {% if form.type.value %}{{ form.type }}{% endif %}

          <div class="control has-icons-left">
            {% bulma_field form.keyword %}
            <span class="icon is-small is-left is-marginless">
              <i class="fa fa-search"></i>
            </span>
          </div>
        </form>
      </li>
    </ul>
  </div>

  {% for schedule in object_list %}
    {% ifchanged %}
      <div class="schedule-date">{{ schedule.date|naturalday }}</div>
    {% endifchanged %}

    <a href="{% url 'schedule:detail' project.slug schedule.pk %}" class="schedule-item">
      <div class="schedule-time">
        {% if schedule.time_from %}
          {{ schedule.time_from|time:"H:i" }} ～
          {% if schedule.time_to %}{{ schedule.time_to|time:"H:i" }}{% endif %}
        {% endif %}
      </div>
      <div class="schedule-name">{{ schedule.name }}</div>
    </a>
  {% empty %}
    <p>
      まだ予定がありません。
    </p>
  {% endfor %}

  <hr>

  <p>
    <a href="{% url 'schedule:create' project.slug %}">予定を作成する</a> /
    <a href="{% url 'schedule:week' project.slug %}">週間表示</a> /
    <a href="{% url 'schedule:month' project.slug %}">月間表示</a>
  </p>

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj extra=request.GET %}
    </nav>
  {% endif %}
{% endblock %}

schedule/templates/schedule/month.html
{% extends "base_project.html" %}

{% load static %}

{% block title %}予定{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/schedule.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li class="is-active"><a href="#">月間</a></li>
    </ul>
  </nav>

  <h2 class="title">月間予定</h2>

  <hr>

  <div class="columns">
    <div class="column is-clearfix has-text-centered">
      <a class="is-pulled-left" href="{% url 'schedule:month' project.slug calendar.previous.year calendar.previous.month  %}">前月</a>
      <a class="is-pulled-right" href="{% url 'schedule:month' project.slug calendar.next.year calendar.next.month %}">次月</a>
      <span>{{ calendar.current | date:"Y年n月" }}</span>
    </div>
  </div>

  <div class="columns schedule-cal-days is-mobile">
    {% for day in calendar.days|slice:":7" %}
      <div class="column schedule-cal-cell">
        {{ day | date:"D" }}
      </div>
    {% endfor %}
  </div>

  <div class="columns is-multiline is-mobile">
    {% for date, schedules in calendar.date_list.items %}
      <div class="column schedule-cal-cell">
        <div class="schedule-cal-date{% if calendar.now == date %} is-today{% endif %}{% if date.weekday == 6 %} is-sunday{% endif %}">
          {% if calendar.current.month == date.month %}
            {{ date | date:"j" }}
          {% else %}
            <span class="has-text-grey">{{ date | date:"n/j" }}</span>
          {% endif %}
        </div>

        {% for schedule in schedules %}
          <a href="{% url 'schedule:detail' project.slug schedule.pk %}" class="schedule-cal-link">
            <div>
              {% if schedule.time_from %}
                <div>
                  {{ schedule.time_from|time:"H:i" }}
                  {% if schedule.time_to %} ～ {{ schedule.time_to|time:"H:i" }}{% endif %}
                </div>
              {% endif %}
              <div class="schedule-cal-name-truncate">{{ schedule.name }}</div>
            </div>
          </a>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

schedule/templates/schedule/update.html
{% extends "base_project.html" %}

{% load bulma %}

{% block title %}予定{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li><a href="{% url 'schedule:detail' project.slug object.pk %}">詳細</a></li>
      <li class="is-active"><a href="#">編集</a></li>
    </ul>
  </nav>

  <h2 class="title">予定編集</h2>

  <hr>

  <form method="post">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p class="has-text-danger">{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      <div class="field columns is-gapless">
        <div class="column is-2">
          <label class="label">{{ field.label }}</label>
        </div>
        <div class="column is-10">
          <div class="control">
            {% bulma_field field %}
          </div>
          {% for error in field.errors %}
            <p class="help is-danger">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}

    <div class="field">
      <div class="control">
        <input class="button is-primary" type="submit" value="更新">
      </div>
    </div>
  </form>
{% endblock %}

schedule/templates/schedule/user_schedule.html
{% extends "base.html" %}

{% load humanize static %}
{% load bulma %}

{% block title %}予定{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/schedule.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'account:user_detail' user_object.username %}">{{ user_object.username }}</a></li>
      <li class="is-active"><a href="#">予定</a></li>
    </ul>
  </nav>

  <h2 class="title">{{ user_object.username }} の予定</h2>

  <hr>

  {% for schedule in object_list %}
    {% ifchanged %}
      <div class="schedule-date">{{ schedule.date|naturalday }}</div>
    {% endifchanged %}

    <a href="{% url 'schedule:detail' schedule.project.slug schedule.pk %}" class="schedule-item">
      <div class="schedule-time">
        {% if schedule.time_from %}
          {{ schedule.time_from|time:"H:i" }} ～
          {% if schedule.time_to %}{{ schedule.time_to|time:"H:i" }}{% endif %}
        {% endif %}
      </div>
      <div class="schedule-name">{{ schedule.name }}</div>
    </a>
  {% empty %}
    <p>
      まだ予定がありません。
    </p>
  {% endfor %}

  <hr>

  {% if is_paginated %}
    <nav class="pagination is-centered" role="navigation" aria-label="pagination">
      {% bulma_pagination page_obj %}
    </nav>
  {% endif %}
{% endblock %}

schedule/templates/schedule/week.html
{% extends "base_project.html" %}

{% load static %}

{% block title %}予定{% endblock %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/schedule.css' %}" />
{% endblock %}

{% block content %}
  <nav class="breadcrumb is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'home:index' %}">トップ</a></li>
      <li><a href="{% url 'home:project_detail' project.slug %}">{{ project.name }}</a></li>
      <li><a href="{% url 'schedule:index' project.slug %}">予定</a></li>
      <li class="is-active"><a href="#">週間</a></li>
    </ul>
  </nav>

  <h2 class="title">週間予定</h2>

  <hr>

  <div class="columns">
    <div class="column is-clearfix has-text-centered">
      <a class="is-pulled-left" href="{% url 'schedule:week' project.slug calendar.previous.year calendar.previous.month calendar.previous.day %}">前週</a>
      <a class="is-pulled-right" href="{% url 'schedule:week' project.slug calendar.next.year calendar.next.month calendar.next.day %}">次週</a>
      <span>{{ calendar.current | date:"Y年n月" }}</span>
    </div>
  </div>

  <div class="columns is-mobile">
    {% for date, schedules in calendar.date_list.items %}
      <div class="column schedule-cal-cell">
        <div class="schedule-cal-date{% if calendar.now == date %} is-today{% endif %}{% if date.weekday == 6 %} is-sunday{% endif %}">
          {% if calendar.current.month != date.month %}{% ifchanged %}{{ date | date:"n" }}/{% endifchanged %}{% endif %}{{ date | date:"j" }}
          <span class="is-hidden-mobile">({{ date | date:"D" }})</span>
        </div>

        {% for schedule in schedules %}
          <a href="{% url 'schedule:detail' project.slug schedule.pk %}" class="schedule-cal-link">
            <div>
              {% if schedule.time_from %}
                <div>
                  {{ schedule.time_from|time:"H:i" }}
                  {% if schedule.time_to %} ～ {{ schedule.time_to|time:"H:i" }}{% endif %}
                </div>
              {% endif %}
              <div class="schedule-cal-name-truncate">{{ schedule.name }}</div>
            </div>
          </a>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}